"""Subclass of FrameWarningKey, which is generated by wxFormBuilder."""

import wx
import AppsSDS.FrameKeyFF as FrameKey
import random
import pathlib
# Implementing FrameWarningKey


class authenticationFrameWarningKey(FrameKey.FrameWarningKey):

	def __init__(self, parent):
		FrameKey.FrameWarningKey.__init__(self, parent)
		self.nilai = random.randint(1700, 1900)
		print (self.nilai)
		self.lisennombor = self.nilai * 4 + 223445435
		self.m_staticText144.SetLabel(str(self.lisennombor))

		# https://www.flaticon.com/authors/pixel-buddha
		# Icon made by [author link] from www.flaticon.com Icon made by [author link] from www.flaticon.com Icon made by [author link] from www.flaticon.com 
		# Icon made by [author link] from www.flaticon.com 

		# Handlers for FrameWarningKey events
		self.pathimage = pathlib.Path.cwd() / "images/symbol/checked.png"
		self.image1 = wx.Image(str(self.pathimage))
		self.re_image1 = self.image1.Rescale(50, 50, quality=wx.IMAGE_QUALITY_NORMAL)
		print (self.pathimage)

		pass

	def m_textCtrl49OnText(self, event):
		# TODO: Implement m_textCtrl49OnText

		pass

	def m_button38OnButtonClick(self, event):
		# TODO: Implement m_button38OnButtonClick

		print ("batal")
		self.Close()
		pass

	def m_button39OnButtonClick(self, event):
		# TODO: Implement m_button39OnButtonClick

		global lisensi
		from AppsSDS.keygenapps.keygen import Key
		from AppsSDS.tempelfile import TempelFile

		self.keynumber = self.m_textCtrl49.GetValue()
		print (self.keynumber)
		lisensi = (self.lisennombor - 223445435) / 4
		print (lisensi)
		self.gen = Key(self.keynumber)

		print (self.gen.verify(lisensi))

		self.verify = self.gen.verify(lisensi)
		# print (self.verify)
		self.yes = TempelFile(self.verify)
		self.yes.compilefile()
		print ("validasi")
		pass


if __name__ == "__main__":
    root = wx.App()
    RunApp = authenticationFrameWarningKey(None)
    RunApp.Show()
    root.MainLoop()
    
    pass
