"""Subclass of DataPeserta, which is generated by wxFormBuilder."""

import wx
import AppsSDS.sds as sds


# Implementing DataPeserta
class DataPesertaSeleksi(sds.DataPeserta):

	def __init__(self, parent):
		sds.DataPeserta.__init__(self, parent)
		self.SetPosition((0, 0))
		# self.SetWindowStyleFlag(wx.LC_REPORT)
# 		self.SetSize(1000,600)
		self.Maximize()
		self.listcolumn = [(0, "No", 50, wx.LIST_FORMAT_CENTER),
						(1, "No Tes", 150, wx.LIST_FORMAT_CENTER),
						(2, "Tanggal Tes", 100, wx.LIST_FORMAT_CENTER),
						(3, "Nama Kandidat", 350, wx.LIST_FORMAT_LEFT),
						(4, "Jenis Kelamin", 100, wx.LIST_FORMAT_CENTER),
# 						(5,"Tanggal Lahir",100),
	# 					(6,"Pendidikan Terakhir",200),
	# 					(7,"Jurusan",100),
	# 					(8,"Kota",100),
	 					(5, "Perusahaan / Instansi", 200, wx.LIST_FORMAT_CENTER),
	 					(6, "Posisi / Jabatan", 200, wx.LIST_FORMAT_CENTER),
						(7, "rowid", 0, wx.LIST_FORMAT_CENTER), ]
				
		for lista in self.listcolumn:
			self.m_ListDataPeserta.\
			InsertColumn(lista[0], lista[1], format=lista[3], width=lista[2])
# 		for index in range(6):
# 			self.m_ListDataPeserta.InsertStringItem(index,"tes")
# 			self.m_ListDataPeserta.SetStringItem(index,1,"tes")
# 			index+=1
# 		
		self.Refresh()
		self.Layout()

	def m_filterOnButtonClick(self, event):
		
		print ("click filter here")
		
		event.Skip()


class DataPesertaTes(sds.DataPeserta):

	def __init__(self, parent):
		sds.DataPeserta.__init__(self, parent)
		self.SetPosition((0, 0))
		# self.SetWindowStyleFlag(wx.LC_REPORT)

# 		self.SetSize(1000,600)
		self.Maximize()
		self.listcolumn = [(0, "No", 50, wx.LIST_FORMAT_CENTER),
					(1, "Nama", 350, wx.LIST_FORMAT_LEFT),
					(2, "Tanggal Tes", 100, wx.LIST_FORMAT_CENTER),
					(3, "Jenis Kelamin", 100, wx.LIST_FORMAT_CENTER),
# 					(4,"Tanggal Lahir",100),
					(4, "Asal Sekolah", 200, wx.LIST_FORMAT_CENTER),
# 					(6,"Jurusan",100),
					(5, "Asal Universitas", 200, wx.LIST_FORMAT_CENTER),
					(6, "Jurusan", 250, wx.LIST_FORMAT_CENTER),
# 					(9,"Kota",100),
# 					(10,"Hobi",100),
# 					(11,"Prestasi Akademik",100),
# 					(12,"Prestasi Non Akademik ",100),
# 					(13,"Ekskul Yang Diikuti ",100),
					(7, "row id ", 0, wx.LIST_FORMAT_CENTER),
					
					]
				
		for lista in self.listcolumn:
# 			print (lista[2])
			self.m_ListDataPeserta.\
			InsertColumn(lista[0], lista[1], format=lista[3], width=lista[2])
		
		self.Refresh()
		self.Layout()


if __name__ == "__main__":
	root = wx.App()
	run = DataPeserta(None)
	run.Show()
	root.MainLoop()

