"""Subclass of DatabaseConn, which is generated by wxFormBuilder."""

import wx
import AppsSDS.sds as sds  # Implementing DatabaseConn

# 
# class DatabaseConn( sds.DatabaseConn ):
# 	
# 	
# 	def __init__( self, parent ):
# 		sds.DatabaseConn.__init__( self, parent )
# 		self.items=["1","2","3","5"]
# 		self.m_listBox2.InsertItems(self.items,0)
# 	
# 	def m_Tutupdbcon(self, event):
# 		self.Close()
# 	
# 	def m_connectdbcon(self, event):
# 
# 		self.SelectLb = self.m_listBox2.GetString(self.m_listBox2.GetSelection())
# 		print (type(self.SelectLb))
# 		self.m_nameconnect.SetLabel(self.SelectLb)
# 		
# 		print ("connect")
# 		self.Refresh()
# 		self.Layout()
# 	
# 	def m_disconnectdbcon(self, event):
# 		a = self.m_nameconnect.SetLabel("")
# 		print ("disconnect")
# 		self.Refresh()
# 		self.Layout()

