"""Subclass of PageAResult, which is generated by wxFormBuilder."""

import wx
import sds


# Implementing PageAResult
class dPageAResult(sds.PageAResult):

	def __init__(self, parent):
		sds.PageAResult.__init__(self, parent)

