"""Subclass of Page4, which is generated by wxFormBuilder."""

import wx
import AppsSDS.sds as sds


# Implementing Page4
class dPage4(sds.Page4):

	def __init__(self, parent):
		sds.Page4.__init__(self, parent)
# 		print ("kesini")
		
	def m_choice5OnChoice(self, event):
		print ("ookok")
		pass

