# """Subclass of KonfigDatabase, which is generated by wxFormBuilder."""
# 
# import wx
# import AppsSDS.sds as sds
# 
# # Implementing KonfigDatabase
# class KonfigDatabase( sds.KonfigDatabase ):
# 	def __init__( self, parent ):
# 		sds.KonfigDatabase.__init__( self, parent )
# 
# 	# Handlers for KonfigDatabase events.
# 	def m_btncreatedatabase( self, event ):
# 		from AppsSDS.DatabaseCR import DatabaseCR as DatabaseCreateRemove
# 		self.OpenDatabscreateremove = DatabaseCreateRemove(self)
# 		self.OpenDatabscreateremove.Show()
# 
# 		# TODO: Implement m_btncreatedatabase
# 		pass
# 
# 	def m_btnconnectdatabase( self, event ):
# 		from AppsSDS.DatabaseConn import DatabaseConn as DatabaseConnection
# 		self.SelectDatabaseConnect = DatabaseConnection(self)
# 		self.SelectDatabaseConnect.Show()
# 		# TODO: Implement m_btnconnectdatabase
# 		pass
# 
# 	def m_btn_closeDatabaseDialog(self,event):
# 		self.Close()
# 		pass
