"""Subclass of Listbox, which is generated by wxFormBuilder."""

import wx
import AppsSDS.temp as temp


# Implementing Listbox
class TempListbox(temp.Listbox1):

    def __init__(self, parent):
        temp.Listbox1.__init__(self, parent)
        self.a = parent
        self.a.SetBackgroundColour(wx.Colour(4, 109, 64))

        print (self.a.op_tomb)
                
    # Handlers for Listbox events.
    def m_tombolcancel_lb(self, event):
        
        print ("tombol cancel")
        self.Close()
        # TODO: Implement m_tombolcancel_lb
        pass

    def tombolok_lb(self, event):
        self.item = self.m_listCtrl1.GetFocusedItem()
        self.Value = self.m_listCtrl1.GetItemText(self.item, 0)
        print (self.Value)
        # self.Value = self.m_listBox1.GetString(self.m_listBox1.GetSelection())

        if self.a.op_tomb == 1:

            self.a.m_panelPage2.textctrl1.SetValue(self.Value)
            print ("kesini")
        elif self.a.op_tomb == 2:

            self.a.m_panelPage2.textctrl2.SetValue(self.Value)
            print ("kesini")			
        elif self.a.op_tomb == 3:

            self.a.m_panelPage2.textctrl3.SetValue(self.Value)
            print ("kesini")			

        elif self.a.op_tomb == 4:

            self.a.m_panelPage2.textctrl4.SetValue(self.Value)
            print ("kesini")			
        elif self.a.op_tomb == 5:

            self.a.m_panelPage2.textctrl5.SetValue(self.Value)
            print ("kesini")			
        elif self.a.op_tomb == 6:

            self.a.m_panelPage2.textctrl6.SetValue(self.Value)
            print ("kesini")			

        else :
            print("salah")
        
        self.Close()
        print ("tombol ok")
        # TODO: Implement tombolok_lb
        pass

    def m_textCtrlKode_listOnText(self, event):
        print ("hhh")
        pass

    def m_listboxselect(self, event):
        self.Close()
        # TODO: Implement m_listboxselect
        pass

    def m_textCtrl_listOnText(self, event):
        self.m_listCtrl1.DeleteAllItems()
        from AppsSDS.controller import sophitiscated_find_search_name
        queryname = self.m_textCtrl1.GetValue()
        klik = sophitiscated_find_search_name.goapps(queryname)
        print (klik)
        self.i = 0
        for items in klik :
            self.m_listCtrl1.InsertStringItem(self.i, klik[self.i][0])
            self.m_listCtrl1.SetItem(self.i, 1, klik[self.i][1])
            self.m_listCtrl1.SetItem(self.i, 2, klik[self.i][2])

            # print (value)
            self.i += 1

        # for key,value in klik.items() :
        #    self.m_listCtrl1.InsertStringItem(i,key)
        #    print (value)
        #    i+=1
        
        print ("textctrl list")

        pass

    def m_button3_cariOnButtonClick(self, event):
        # deleted_item = self.m_listBox1.GetStringSelection()
        # numOfItems=self.m_listBox1.GetCount()
        # itemsArr = []
        # for i in range(numOfItems):
        #     x = self.m_listBox1.GetString(i)
        #     if x != deleted_item:
        #         itemsArr.append(x)
        # m_listBox1Choices = itemsArr
        # self.m_listBox1.Clear()
        # self.m_listBox1.Set(m_listBox1Choices)
        # self.m_listBox1.Update()	
        self.m_listCtrl1.DeleteAllItems()
        from AppsSDS.controller import sophitiscated_find_search_name
        queryname = self.m_button3.GetValue()
        klik = sophitiscated_find_search_name.goapps_kode(queryname)
        # print (klik)
        print ("berhasil")
        # for key,value in klik.items() :
        #    self.m_listCtrl1.InsertStringItem(i,key)
        #    print (value)
        #    i+=1
        self.i = 0
        for items in klik :
            self.m_listCtrl1.InsertStringItem(self.i, klik[self.i][0])
            self.m_listCtrl1.SetItem(self.i, 1, klik[self.i][1])
            self.m_listCtrl1.SetItem(self.i, 2, klik[self.i][2])
            print (items)

            # print (value)
            self.i += 1

        print ("tombol cari on button")
        pass
    
    def m_listCtrl1OnLeftDClick(self, event):
        self.item = self.m_listCtrl1.GetFocusedItem()
        self.Value = self.m_listCtrl1.GetItemText(self.item, 0)
        print (self.Value)
        # self.Value = self.m_listBox1.GetString(self.m_listBox1.GetSelection())

        if self.a.op_tomb == 1:

            self.a.m_panelPage2.textctrl1.SetValue(self.Value)
            print ("kesini")
        elif self.a.op_tomb == 2:

            self.a.m_panelPage2.textctrl2.SetValue(self.Value)
            print ("kesini")			
        elif self.a.op_tomb == 3:

            self.a.m_panelPage2.textctrl3.SetValue(self.Value)
            print ("kesini")			

        elif self.a.op_tomb == 4:

            self.a.m_panelPage2.textctrl4.SetValue(self.Value)
            print ("kesini")			
        elif self.a.op_tomb == 5:

            self.a.m_panelPage2.textctrl5.SetValue(self.Value)
            print ("kesini")			
        elif self.a.op_tomb == 6:

            self.a.m_panelPage2.textctrl6.SetValue(self.Value)
            print ("kesini")			

        else :
            print("salah")
        
        self.Close()       
    
        pass
